name = "swole-tracker"
main = ".open-next/worker.js"
compatibility_date = "2024-10-03"
account_id = "{{ CLOUDFLARE_ACCOUNT_ID }}"

[env.dev]
name = "swole-tracker-dev"

  [env.dev.d1_databases]
  # D1 database binding for development
  DB = { id = "{{ D1_DB_ID }}" }

[env.staging]
name = "swole-tracker-staging"

  [env.staging.d1_databases]
  DB = { id = "{{ D1_DB_ID }}" }

[env.production]
name = "swole-tracker-prod"

  [env.production.d1_databases]
  DB = { id = "{{ D1_DB_ID }}" }

[env.preview]
name = "swole-tracker-preview"

  [env.preview.d1_databases]
  DB = { id = "{{ D1_DB_ID }}" }
