name = "swole-tracker"
# main is handled by next-on-pages build output
compatibility_date = "2024-10-03"
account_id = "{{ CLOUDFLARE_ACCOUNT_ID }}"

[env.dev]
name = "swole-tracker-dev"

  [env.dev.d1_databases]
  # D1 database binding for development
  DB = { id = "{{ D1_DB_ID }}" }

[env.staging]
name = "swole-tracker-staging"

  [env.staging.d1_databases]
  DB = { id = "{{ D1_DB_ID }}" }

[env.production]
name = "swole-tracker-prod"

  [env.production.d1_databases]
  DB = { id = "{{ D1_DB_ID }}" }

  # Custom domain configuration for production
  [[env.production.routes]]
  pattern = "workout.stevenduong.com/*"
  zone_name = "workout.stevenduong.com"

[env.preview]
name = "swole-tracker-preview"

  [env.preview.d1_databases]
  DB = { id = "{{ D1_DB_ID }}" }

  # Custom domain configuration for preview
  [[env.preview.routes]]
  pattern = "preview.stevenduong.com/*"
  zone_name = "preview.stevenduong.com"
