CREATE TABLE "swole-tracker_session_exercise" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_session_exercise_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"sessionId" integer NOT NULL,
	"templateExerciseId" integer,
	"exerciseName" varchar(256) NOT NULL,
	"weight" numeric(6, 2),
	"reps" integer,
	"sets" integer,
	"unit" varchar(10) DEFAULT 'kg' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "swole-tracker_template_exercise" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_template_exercise_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"templateId" integer NOT NULL,
	"exerciseName" varchar(256) NOT NULL,
	"orderIndex" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "swole-tracker_user_preferences" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_user_preferences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"defaultWeightUnit" varchar(10) DEFAULT 'kg' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "swole-tracker_user_preferences_userId_unique" UNIQUE("userId")
);
--> statement-breakpoint
CREATE TABLE "swole-tracker_workout_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_workout_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"templateId" integer NOT NULL,
	"workoutDate" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "swole-tracker_workout_template" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_workout_template_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"userId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "swole-tracker_session_exercise" ADD CONSTRAINT "swole-tracker_session_exercise_sessionId_swole-tracker_workout_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."swole-tracker_workout_session"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "swole-tracker_session_exercise" ADD CONSTRAINT "swole-tracker_session_exercise_templateExerciseId_swole-tracker_template_exercise_id_fk" FOREIGN KEY ("templateExerciseId") REFERENCES "public"."swole-tracker_template_exercise"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "swole-tracker_template_exercise" ADD CONSTRAINT "swole-tracker_template_exercise_templateId_swole-tracker_workout_template_id_fk" FOREIGN KEY ("templateId") REFERENCES "public"."swole-tracker_workout_template"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "swole-tracker_workout_session" ADD CONSTRAINT "swole-tracker_workout_session_templateId_swole-tracker_workout_template_id_fk" FOREIGN KEY ("templateId") REFERENCES "public"."swole-tracker_workout_template"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "session_exercise_user_id_idx" ON "swole-tracker_session_exercise" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "session_exercise_session_id_idx" ON "swole-tracker_session_exercise" USING btree ("sessionId");--> statement-breakpoint
CREATE INDEX "session_exercise_template_exercise_id_idx" ON "swole-tracker_session_exercise" USING btree ("templateExerciseId");--> statement-breakpoint
CREATE INDEX "session_exercise_name_idx" ON "swole-tracker_session_exercise" USING btree ("exerciseName");--> statement-breakpoint
CREATE INDEX "template_exercise_user_id_idx" ON "swole-tracker_template_exercise" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "template_exercise_template_id_idx" ON "swole-tracker_template_exercise" USING btree ("templateId");--> statement-breakpoint
CREATE INDEX "template_exercise_order_idx" ON "swole-tracker_template_exercise" USING btree ("templateId","orderIndex");--> statement-breakpoint
CREATE INDEX "user_preferences_user_id_idx" ON "swole-tracker_user_preferences" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "swole-tracker_workout_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "session_template_id_idx" ON "swole-tracker_workout_session" USING btree ("templateId");--> statement-breakpoint
CREATE INDEX "session_workout_date_idx" ON "swole-tracker_workout_session" USING btree ("workoutDate");--> statement-breakpoint
CREATE INDEX "template_user_id_idx" ON "swole-tracker_workout_template" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "template_name_idx" ON "swole-tracker_workout_template" USING btree ("name");