CREATE TABLE "swole-tracker_daily_joke" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_daily_joke_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"joke" text NOT NULL,
	"aiModel" varchar(100) NOT NULL,
	"prompt" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE INDEX "daily_joke_user_id_idx" ON "swole-tracker_daily_joke" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "daily_joke_created_at_idx" ON "swole-tracker_daily_joke" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "daily_joke_user_date_idx" ON "swole-tracker_daily_joke" USING btree ("user_id","createdAt");