CREATE TABLE "swole-tracker_whoop_workout" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_whoop_workout_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"whoopWorkoutId" varchar(256) NOT NULL,
	"start" timestamp with time zone NOT NULL,
	"end" timestamp with time zone NOT NULL,
	"timezone_offset" varchar(20),
	"sport_name" varchar(100),
	"score_state" varchar(50),
	"score" json,
	"during" json,
	"zone_duration" json,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "swole-tracker_whoop_workout_whoopWorkoutId_unique" UNIQUE("whoopWorkoutId")
);
--> statement-breakpoint
CREATE TABLE "swole-tracker_user_integration" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_user_integration_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"provider" varchar(50) NOT NULL,
	"accessToken" text NOT NULL,
	"refreshToken" text,
	"expiresAt" timestamp with time zone,
	"scope" varchar(500),
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "whoop_workout_user_id_idx" ON "swole-tracker_whoop_workout" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "whoop_workout_workout_id_idx" ON "swole-tracker_whoop_workout" USING btree ("whoopWorkoutId");--> statement-breakpoint
CREATE INDEX "whoop_workout_start_idx" ON "swole-tracker_whoop_workout" USING btree ("start");--> statement-breakpoint
CREATE INDEX "whoop_workout_user_start_idx" ON "swole-tracker_whoop_workout" USING btree ("user_id","start");--> statement-breakpoint
CREATE INDEX "user_integration_user_id_idx" ON "swole-tracker_user_integration" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_integration_provider_idx" ON "swole-tracker_user_integration" USING btree ("provider");--> statement-breakpoint
CREATE INDEX "user_integration_user_provider_idx" ON "swole-tracker_user_integration" USING btree ("user_id","provider");