CREATE TABLE "swole-tracker_exercise_link" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_exercise_link_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"templateExerciseId" integer NOT NULL,
	"masterExerciseId" integer NOT NULL,
	"user_id" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "exercise_link_template_exercise_unique" UNIQUE("templateExerciseId")
);
--> statement-breakpoint
CREATE TABLE "swole-tracker_whoop_workout" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_whoop_workout_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"whoopWorkoutId" varchar(256) NOT NULL,
	"start" timestamp with time zone NOT NULL,
	"end" timestamp with time zone NOT NULL,
	"timezone_offset" varchar(20),
	"sport_name" varchar(100),
	"score_state" varchar(50),
	"score" json,
	"during" json,
	"zone_duration" json,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "swole-tracker_whoop_workout_whoopWorkoutId_unique" UNIQUE("whoopWorkoutId")
);
--> statement-breakpoint
CREATE TABLE "swole-tracker_master_exercise" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_master_exercise_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"name" varchar(256) NOT NULL,
	"normalizedName" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "master_exercise_user_name_unique" UNIQUE("user_id","normalizedName")
);
--> statement-breakpoint
CREATE TABLE "swole-tracker_rate_limit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_rate_limit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"endpoint" varchar(100) NOT NULL,
	"requests" integer DEFAULT 0 NOT NULL,
	"windowStart" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "swole-tracker_webhook_event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_webhook_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider" varchar(50) NOT NULL,
	"eventType" varchar(100) NOT NULL,
	"userId" varchar(256),
	"externalUserId" varchar(256),
	"externalEntityId" varchar(256),
	"payload" json,
	"headers" json,
	"status" varchar(20) DEFAULT 'received' NOT NULL,
	"error" text,
	"processingTime" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"processedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "swole-tracker_external_workout_whoop" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "swole-tracker_external_workout_whoop" CASCADE;--> statement-breakpoint
ALTER TABLE "swole-tracker_session_exercise" DROP CONSTRAINT "swole-tracker_session_exercise_templateExerciseId_swole-tracker_template_exercise_id_fk";
--> statement-breakpoint
ALTER TABLE "swole-tracker_session_exercise" ADD COLUMN "setOrder" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "swole-tracker_session_exercise" ADD COLUMN "rpe" smallint;--> statement-breakpoint
ALTER TABLE "swole-tracker_session_exercise" ADD COLUMN "rest_seconds" integer;--> statement-breakpoint
ALTER TABLE "swole-tracker_session_exercise" ADD COLUMN "is_estimate" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "swole-tracker_session_exercise" ADD COLUMN "is_default_applied" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "swole-tracker_template_exercise" ADD COLUMN "linkingRejected" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "swole-tracker_user_preferences" ADD COLUMN "predictive_defaults_enabled" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "swole-tracker_user_preferences" ADD COLUMN "right_swipe_action" varchar(32) DEFAULT 'collapse_expand' NOT NULL;--> statement-breakpoint
ALTER TABLE "swole-tracker_workout_session" ADD COLUMN "theme_used" varchar(20);--> statement-breakpoint
ALTER TABLE "swole-tracker_workout_session" ADD COLUMN "device_type" varchar(20);--> statement-breakpoint
ALTER TABLE "swole-tracker_workout_session" ADD COLUMN "perf_metrics" json;--> statement-breakpoint
ALTER TABLE "swole-tracker_exercise_link" ADD CONSTRAINT "swole-tracker_exercise_link_templateExerciseId_swole-tracker_template_exercise_id_fk" FOREIGN KEY ("templateExerciseId") REFERENCES "public"."swole-tracker_template_exercise"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "swole-tracker_exercise_link" ADD CONSTRAINT "swole-tracker_exercise_link_masterExerciseId_swole-tracker_master_exercise_id_fk" FOREIGN KEY ("masterExerciseId") REFERENCES "public"."swole-tracker_master_exercise"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "exercise_link_template_exercise_idx" ON "swole-tracker_exercise_link" USING btree ("templateExerciseId");--> statement-breakpoint
CREATE INDEX "exercise_link_master_exercise_idx" ON "swole-tracker_exercise_link" USING btree ("masterExerciseId");--> statement-breakpoint
CREATE INDEX "exercise_link_user_id_idx" ON "swole-tracker_exercise_link" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "external_workout_whoop_user_id_idx" ON "swole-tracker_whoop_workout" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "external_workout_whoop_workout_id_idx" ON "swole-tracker_whoop_workout" USING btree ("whoopWorkoutId");--> statement-breakpoint
CREATE INDEX "external_workout_whoop_start_idx" ON "swole-tracker_whoop_workout" USING btree ("start");--> statement-breakpoint
CREATE INDEX "external_workout_whoop_user_start_idx" ON "swole-tracker_whoop_workout" USING btree ("user_id","start");--> statement-breakpoint
CREATE INDEX "master_exercise_user_id_idx" ON "swole-tracker_master_exercise" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "master_exercise_name_idx" ON "swole-tracker_master_exercise" USING btree ("name");--> statement-breakpoint
CREATE INDEX "master_exercise_normalized_name_idx" ON "swole-tracker_master_exercise" USING btree ("normalizedName");--> statement-breakpoint
CREATE INDEX "master_exercise_user_normalized_idx" ON "swole-tracker_master_exercise" USING btree ("user_id","normalizedName");--> statement-breakpoint
CREATE INDEX "rate_limit_user_endpoint_idx" ON "swole-tracker_rate_limit" USING btree ("user_id","endpoint");--> statement-breakpoint
CREATE INDEX "rate_limit_window_idx" ON "swole-tracker_rate_limit" USING btree ("windowStart");--> statement-breakpoint
CREATE INDEX "webhook_event_provider_idx" ON "swole-tracker_webhook_event" USING btree ("provider");--> statement-breakpoint
CREATE INDEX "webhook_event_type_idx" ON "swole-tracker_webhook_event" USING btree ("eventType");--> statement-breakpoint
CREATE INDEX "webhook_event_user_id_idx" ON "swole-tracker_webhook_event" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "webhook_event_external_user_id_idx" ON "swole-tracker_webhook_event" USING btree ("externalUserId");--> statement-breakpoint
CREATE INDEX "webhook_event_status_idx" ON "swole-tracker_webhook_event" USING btree ("status");--> statement-breakpoint
CREATE INDEX "webhook_event_created_at_idx" ON "swole-tracker_webhook_event" USING btree ("createdAt");--> statement-breakpoint
ALTER TABLE "swole-tracker_session_exercise" ADD CONSTRAINT "swole-tracker_session_exercise_templateExerciseId_swole-tracker_template_exercise_id_fk" FOREIGN KEY ("templateExerciseId") REFERENCES "public"."swole-tracker_template_exercise"("id") ON DELETE set null ON UPDATE no action;