-- Add rate limiting table for API request tracking
CREATE TABLE "swole-tracker_rate_limit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_rate_limit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"endpoint" varchar(100) NOT NULL,
	"requests" integer DEFAULT 0 NOT NULL,
	"windowStart" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "rate_limit_user_endpoint_idx" ON "swole-tracker_rate_limit" USING btree ("user_id","endpoint");--> statement-breakpoint
CREATE INDEX "rate_limit_window_idx" ON "swole-tracker_rate_limit" USING btree ("windowStart");
