-- Add webhook events table for debugging and audit trail
CREATE TABLE "swole-tracker_webhook_event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_webhook_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider" varchar(50) NOT NULL,
	"eventType" varchar(100) NOT NULL,
	"userId" varchar(256),
	"externalUserId" varchar(256),
	"externalEntityId" varchar(256),
	"payload" json,
	"headers" json,
	"status" varchar(20) DEFAULT 'received' NOT NULL,
	"error" text,
	"processingTime" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"processedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "webhook_event_provider_idx" ON "swole-tracker_webhook_event" USING btree ("provider");--> statement-breakpoint
CREATE INDEX "webhook_event_type_idx" ON "swole-tracker_webhook_event" USING btree ("eventType");--> statement-breakpoint
CREATE INDEX "webhook_event_user_id_idx" ON "swole-tracker_webhook_event" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "webhook_event_external_user_id_idx" ON "swole-tracker_webhook_event" USING btree ("externalUserId");--> statement-breakpoint
CREATE INDEX "webhook_event_status_idx" ON "swole-tracker_webhook_event" USING btree ("status");--> statement-breakpoint
CREATE INDEX "webhook_event_created_at_idx" ON "swole-tracker_webhook_event" USING btree ("createdAt");
