CREATE TABLE "swole-tracker_health_advice" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_health_advice_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"sessionId" integer NOT NULL,
	"request" json NOT NULL,
	"response" json NOT NULL,
	"readiness_rho" numeric(3, 2),
	"overload_multiplier" numeric(3, 2),
	"session_predicted_chance" numeric(3, 2),
	"user_accepted_suggestions" integer DEFAULT 0 NOT NULL,
	"total_suggestions" integer NOT NULL,
	"response_time_ms" integer,
	"model_used" varchar(100),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "health_advice_user_session_unique" UNIQUE("user_id","sessionId")
);
--> statement-breakpoint
ALTER TABLE "swole-tracker_health_advice" ADD CONSTRAINT "swole-tracker_health_advice_sessionId_swole-tracker_workout_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."swole-tracker_workout_session"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "health_advice_user_id_idx" ON "swole-tracker_health_advice" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "health_advice_session_id_idx" ON "swole-tracker_health_advice" USING btree ("sessionId");--> statement-breakpoint
CREATE INDEX "health_advice_created_at_idx" ON "swole-tracker_health_advice" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "health_advice_user_created_idx" ON "swole-tracker_health_advice" USING btree ("user_id","createdAt");