CREATE TABLE "swole-tracker_user_migration_mapping" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_user_migration_mapping_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerk_user_id" varchar(256) NOT NULL,
	"supabase_user_id" varchar(256) NOT NULL,
	"email" varchar(256) NOT NULL,
	"migrated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"migration_status" varchar(50) DEFAULT 'pending' NOT NULL,
	"migration_notes" text,
	CONSTRAINT "swole-tracker_user_migration_mapping_clerk_user_id_unique" UNIQUE("clerk_user_id"),
	CONSTRAINT "swole-tracker_user_migration_mapping_supabase_user_id_unique" UNIQUE("supabase_user_id")
);
--> statement-breakpoint
CREATE INDEX "user_migration_clerk_id_idx" ON "swole-tracker_user_migration_mapping" USING btree ("clerk_user_id");--> statement-breakpoint
CREATE INDEX "user_migration_supabase_id_idx" ON "swole-tracker_user_migration_mapping" USING btree ("supabase_user_id");--> statement-breakpoint
CREATE INDEX "user_migration_email_idx" ON "swole-tracker_user_migration_mapping" USING btree ("email");