-- Migration: Add exercise linking functionality
-- This migration creates a master exercises table and links template exercises to it

-- Master Exercises Table
-- This stores unique exercises that can be shared across templates
CREATE TABLE "swole-tracker_master_exercise" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_master_exercise_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"name" varchar(256) NOT NULL,
	"normalized_name" varchar(256) NOT NULL, -- Lowercased, trimmed name for fuzzy matching
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);

-- Exercise Links Table
-- This table maps template exercises to master exercises
CREATE TABLE "swole-tracker_exercise_link" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "swole-tracker_exercise_link_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"template_exercise_id" integer NOT NULL,
	"master_exercise_id" integer NOT NULL,
	"user_id" varchar(256) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "swole-tracker_exercise_link_template_exercise_id_swole-tracker_template_exercise_id_fk" FOREIGN KEY ("template_exercise_id") REFERENCES "swole-tracker_template_exercise"("id") ON DELETE cascade,
	CONSTRAINT "swole-tracker_exercise_link_master_exercise_id_swole-tracker_master_exercise_id_fk" FOREIGN KEY ("master_exercise_id") REFERENCES "swole-tracker_master_exercise"("id") ON DELETE cascade
);

-- Indexes for performance
CREATE INDEX "master_exercise_user_id_idx" ON "swole-tracker_master_exercise" USING btree ("user_id");
CREATE INDEX "master_exercise_name_idx" ON "swole-tracker_master_exercise" USING btree ("name");
CREATE INDEX "master_exercise_normalized_name_idx" ON "swole-tracker_master_exercise" USING btree ("normalized_name");
CREATE INDEX "master_exercise_user_normalized_idx" ON "swole-tracker_master_exercise" USING btree ("user_id","normalized_name");

CREATE INDEX "exercise_link_template_exercise_idx" ON "swole-tracker_exercise_link" USING btree ("template_exercise_id");
CREATE INDEX "exercise_link_master_exercise_idx" ON "swole-tracker_exercise_link" USING btree ("master_exercise_id");
CREATE INDEX "exercise_link_user_id_idx" ON "swole-tracker_exercise_link" USING btree ("user_id");

-- Unique constraint: each template exercise can only be linked to one master exercise
CREATE UNIQUE INDEX "exercise_link_template_exercise_unique" ON "swole-tracker_exercise_link" USING btree ("template_exercise_id");

-- Unique constraint: prevent duplicate master exercise names per user
CREATE UNIQUE INDEX "master_exercise_user_name_unique" ON "swole-tracker_master_exercise" USING btree ("user_id","normalized_name");
