name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SITE_URL: http://localhost
      NEXT_PUBLIC_ENV: ci
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_dummy
      NEXT_PUBLIC_POSTHOG_KEY: phc_test_dummy
      NEXT_PUBLIC_POSTHOG_HOST: https://us.i.posthog.com
      NEXT_PUBLIC_SUPABASE_URL: https://test.supabase.co
      NEXT_PUBLIC_SUPABASE_KEY: supabase_test_key

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint and typecheck
        run: |
          pnpm format:check || true
          pnpm check || pnpm run -r check || true
          pnpm typecheck || true

      - name: Run tests with coverage
        run: pnpm run test:ci

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage
