name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SITE_URL: http://localhost
      NEXT_PUBLIC_ENV: ci
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_dummy
      NEXT_PUBLIC_POSTHOG_KEY: phc_test_dummy
      NEXT_PUBLIC_POSTHOG_HOST: https://us.i.posthog.com
      NEXT_PUBLIC_SUPABASE_URL: https://test.supabase.co
      NEXT_PUBLIC_SUPABASE_KEY: supabase_test_key
      # Additional environment variables for CI
      CLERK_SECRET_KEY: sk_test_dummy
      DATABASE_URL: postgresql://postgres:password@localhost:5432/test_db
      NODE_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint and typecheck
        run: |
          bun run format:check || true
          bun check || bun run check || true
          bun run typecheck || true

      - name: Run tests with coverage
        run: bun run test:ci

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage
